/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as MyvaultRouteImport } from './routes/myvault'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationIdRouteImport } from './routes/location.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as MyvaultIdEditRouteImport } from './routes/myvault.$id.edit'
import { Route as EventsIdRegisterRouteImport } from './routes/events.$id.register'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const MyvaultRoute = MyvaultRouteImport.update({
  id: '/myvault',
  path: '/myvault',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIdRoute = LocationIdRouteImport.update({
  id: '/location/$id',
  path: '/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const MyvaultIdEditRoute = MyvaultIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => MyvaultRoute,
} as any)
const EventsIdRegisterRoute = EventsIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/myvault': typeof MyvaultRouteWithChildren
  '/vault': typeof VaultRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/location/$id': typeof LocationIdRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
  '/myvault/$id/edit': typeof MyvaultIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/myvault': typeof MyvaultRouteWithChildren
  '/vault': typeof VaultRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/location/$id': typeof LocationIdRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
  '/myvault/$id/edit': typeof MyvaultIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/myvault': typeof MyvaultRouteWithChildren
  '/vault': typeof VaultRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/location/$id': typeof LocationIdRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
  '/myvault/$id/edit': typeof MyvaultIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/donate'
    | '/events'
    | '/home'
    | '/map'
    | '/marketplace'
    | '/myvault'
    | '/vault'
    | '/events/$id'
    | '/location/$id'
    | '/events/$id/register'
    | '/myvault/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/donate'
    | '/events'
    | '/home'
    | '/map'
    | '/marketplace'
    | '/myvault'
    | '/vault'
    | '/events/$id'
    | '/location/$id'
    | '/events/$id/register'
    | '/myvault/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/donate'
    | '/events'
    | '/home'
    | '/map'
    | '/marketplace'
    | '/myvault'
    | '/vault'
    | '/events/$id'
    | '/location/$id'
    | '/events/$id/register'
    | '/myvault/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyvaultRoute: typeof MyvaultRouteWithChildren
  VaultRoute: typeof VaultRoute
  LocationIdRoute: typeof LocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myvault': {
      id: '/myvault'
      path: '/myvault'
      fullPath: '/myvault'
      preLoaderRoute: typeof MyvaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$id': {
      id: '/location/$id'
      path: '/location/$id'
      fullPath: '/location/$id'
      preLoaderRoute: typeof LocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/myvault/$id/edit': {
      id: '/myvault/$id/edit'
      path: '/$id/edit'
      fullPath: '/myvault/$id/edit'
      preLoaderRoute: typeof MyvaultIdEditRouteImport
      parentRoute: typeof MyvaultRoute
    }
    '/events/$id/register': {
      id: '/events/$id/register'
      path: '/register'
      fullPath: '/events/$id/register'
      preLoaderRoute: typeof EventsIdRegisterRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface EventsIdRouteChildren {
  EventsIdRegisterRoute: typeof EventsIdRegisterRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdRegisterRoute: EventsIdRegisterRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRouteWithChildren
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRouteWithChildren,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MyvaultRouteChildren {
  MyvaultIdEditRoute: typeof MyvaultIdEditRoute
}

const MyvaultRouteChildren: MyvaultRouteChildren = {
  MyvaultIdEditRoute: MyvaultIdEditRoute,
}

const MyvaultRouteWithChildren =
  MyvaultRoute._addFileChildren(MyvaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyvaultRoute: MyvaultRouteWithChildren,
  VaultRoute: VaultRoute,
  LocationIdRoute: LocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
